import { MigrationInterface, QueryRunner } from 'typeorm';

export class MovementPublicCodes1790121600000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE movements ADD COLUMN codigo_movimentacao varchar(30);
      CREATE SEQUENCE seq_movimentacao_ent OWNED BY movements.codigo_movimentacao;
      CREATE SEQUENCE seq_movimentacao_sai OWNED BY movements.codigo_movimentacao;
      CREATE SEQUENCE seq_movimentacao_rev OWNED BY movements.codigo_movimentacao;
      DO $$
      DECLARE row_record record; prefix text; number_value bigint;
      BEGIN
        FOR row_record IN SELECT id, type FROM movements
          WHERE type IN ('ENTRADA_EXTERNA','SAIDA_EXTERNA','REVISAO')
          ORDER BY occurred_at, created_at, id
        LOOP
          prefix := CASE row_record.type WHEN 'ENTRADA_EXTERNA' THEN 'ENT' WHEN 'SAIDA_EXTERNA' THEN 'SAI' ELSE 'REV' END;
          number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
          UPDATE movements SET codigo_movimentacao = prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0') WHERE id = row_record.id;
        END LOOP;
      END $$;
      ALTER TABLE movements ADD CONSTRAINT uq_movements_public_code UNIQUE (codigo_movimentacao);
      CREATE OR REPLACE FUNCTION assign_movement_public_code() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE prefix text; number_value bigint;
      BEGIN
        IF TG_OP = 'UPDATE' THEN
          IF NEW.codigo_movimentacao IS DISTINCT FROM OLD.codigo_movimentacao OR NEW.type IS DISTINCT FROM OLD.type THEN
            RAISE EXCEPTION 'Movement code and type are immutable';
          END IF;
          RETURN NEW;
        END IF;
        IF NEW.codigo_movimentacao IS NOT NULL THEN RAISE EXCEPTION 'Movement code must be generated by the database'; END IF;
        prefix := CASE NEW.type WHEN 'ENTRADA_EXTERNA' THEN 'ENT' WHEN 'SAIDA_EXTERNA' THEN 'SAI' WHEN 'REVISAO' THEN 'REV' ELSE NULL END;
        IF prefix IS NOT NULL THEN
          number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
          NEW.codigo_movimentacao := prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0');
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER movement_public_code BEFORE INSERT OR UPDATE ON movements
        FOR EACH ROW EXECUTE FUNCTION assign_movement_public_code();
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TRIGGER movement_public_code ON movements;
      DROP FUNCTION assign_movement_public_code();
      ALTER TABLE movements DROP COLUMN codigo_movimentacao;
    `);
  }
}
