import { MigrationInterface, QueryRunner } from 'typeorm';

export class ShipmentLifecyclePublicCodes1790208000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE shipments ADD COLUMN codigo_movimentacao varchar(30);
      DROP TRIGGER shipment_immutable ON shipments;
      DROP FUNCTION IF EXISTS assign_shipment_public_code();
      ALTER TABLE movements DROP CONSTRAINT uq_movements_public_code;
      CREATE UNIQUE INDEX uq_movements_standalone_public_code ON movements(codigo_movimentacao) WHERE shipment_id IS NULL;

      WITH linked_codes AS (
        SELECT shipment_id, min(codigo_movimentacao) AS codigo_movimentacao
        FROM movements WHERE shipment_id IS NOT NULL AND codigo_movimentacao IS NOT NULL GROUP BY shipment_id
      )
      UPDATE shipments shipment SET codigo_movimentacao = linked.codigo_movimentacao
      FROM linked_codes linked WHERE shipment.id = linked.shipment_id;

      UPDATE movements movement SET codigo_movimentacao = shipment.codigo_movimentacao
      FROM shipments shipment
      WHERE movement.shipment_id = shipment.id AND shipment.codigo_movimentacao IS NOT NULL
        AND movement.codigo_movimentacao IS DISTINCT FROM shipment.codigo_movimentacao;

      DO $$
      DECLARE row_record record; prefix text; number_value bigint;
      BEGIN
        FOR row_record IN SELECT id, origin_sector, destination_sector FROM shipments
          WHERE codigo_movimentacao IS NULL ORDER BY created_at, id
        LOOP
          prefix := CASE WHEN row_record.destination_sector = 'REVISAO' THEN 'ENT' ELSE 'SAI' END;
          number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
          UPDATE shipments SET codigo_movimentacao = prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0')
          WHERE id = row_record.id;
        END LOOP;
      END $$;

      ALTER TABLE shipments ALTER COLUMN codigo_movimentacao SET NOT NULL;
      ALTER TABLE shipments ADD CONSTRAINT uq_shipments_public_code UNIQUE (codigo_movimentacao);

      CREATE FUNCTION assign_shipment_public_code() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE prefix text; number_value bigint;
      BEGIN
        IF TG_OP = 'UPDATE' THEN
          IF NEW.codigo_movimentacao IS DISTINCT FROM OLD.codigo_movimentacao THEN RAISE EXCEPTION 'Shipment public code is immutable'; END IF;
          RETURN NEW;
        END IF;
        IF NEW.codigo_movimentacao IS NOT NULL THEN RAISE EXCEPTION 'Shipment public code must be generated by the database'; END IF;
        prefix := CASE WHEN NEW.destination_sector = 'REVISAO' THEN 'ENT' ELSE 'SAI' END;
        number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
        NEW.codigo_movimentacao := prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0');
        RETURN NEW;
      END $$;
      CREATE TRIGGER shipment_public_code BEFORE INSERT OR UPDATE ON shipments
        FOR EACH ROW EXECUTE FUNCTION assign_shipment_public_code();
      CREATE TRIGGER shipment_immutable BEFORE UPDATE OR DELETE ON shipments
        FOR EACH ROW EXECUTE FUNCTION protect_shipment_history();

      CREATE OR REPLACE FUNCTION assign_movement_public_code() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE prefix text; number_value bigint;
      BEGIN
        IF TG_OP = 'UPDATE' THEN
          IF NEW.codigo_movimentacao IS DISTINCT FROM OLD.codigo_movimentacao OR NEW.type IS DISTINCT FROM OLD.type THEN
            RAISE EXCEPTION 'Movement code and type are immutable';
          END IF;
          RETURN NEW;
        END IF;
        IF NEW.codigo_movimentacao IS NOT NULL THEN RAISE EXCEPTION 'Movement code must be generated by the database'; END IF;
        IF NEW.shipment_id IS NOT NULL THEN
          SELECT codigo_movimentacao INTO NEW.codigo_movimentacao FROM shipments WHERE id = NEW.shipment_id;
          IF NEW.codigo_movimentacao IS NULL THEN RAISE EXCEPTION 'Shipment public code not found'; END IF;
          RETURN NEW;
        END IF;
        prefix := CASE NEW.type WHEN 'ENTRADA_EXTERNA' THEN 'ENT' WHEN 'SAIDA_EXTERNA' THEN 'SAI' WHEN 'REVISAO' THEN 'REV' ELSE NULL END;
        IF prefix IS NOT NULL THEN
          number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
          NEW.codigo_movimentacao := prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0');
        END IF;
        RETURN NEW;
      END $$;
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TRIGGER shipment_public_code ON shipments;
      DROP FUNCTION assign_shipment_public_code();
      ALTER TABLE shipments DROP CONSTRAINT uq_shipments_public_code;
      ALTER TABLE shipments DROP COLUMN codigo_movimentacao;
      DROP INDEX uq_movements_standalone_public_code;
      DROP TRIGGER movement_public_code ON movements;

      DO $$
      DECLARE row_record record; prefix text; number_value bigint;
      BEGIN
        FOR row_record IN
          SELECT id, type FROM (
            SELECT id, type, row_number() OVER (PARTITION BY codigo_movimentacao ORDER BY occurred_at, created_at, id) AS occurrence
            FROM movements WHERE codigo_movimentacao IS NOT NULL
          ) duplicated WHERE occurrence > 1
        LOOP
          prefix := CASE row_record.type WHEN 'ENTRADA_EXTERNA' THEN 'ENT' WHEN 'SAIDA_EXTERNA' THEN 'SAI' WHEN 'REVISAO' THEN 'REV' ELSE NULL END;
          IF prefix IS NOT NULL THEN
            number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
            UPDATE movements SET codigo_movimentacao = prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0') WHERE id = row_record.id;
          END IF;
        END LOOP;
      END $$;
      ALTER TABLE movements ADD CONSTRAINT uq_movements_public_code UNIQUE (codigo_movimentacao);
      CREATE OR REPLACE FUNCTION assign_movement_public_code() RETURNS trigger LANGUAGE plpgsql AS $$
      DECLARE prefix text; number_value bigint;
      BEGIN
        IF TG_OP = 'UPDATE' THEN
          IF NEW.codigo_movimentacao IS DISTINCT FROM OLD.codigo_movimentacao OR NEW.type IS DISTINCT FROM OLD.type THEN RAISE EXCEPTION 'Movement code and type are immutable'; END IF;
          RETURN NEW;
        END IF;
        IF NEW.codigo_movimentacao IS NOT NULL THEN RAISE EXCEPTION 'Movement code must be generated by the database'; END IF;
        prefix := CASE NEW.type WHEN 'ENTRADA_EXTERNA' THEN 'ENT' WHEN 'SAIDA_EXTERNA' THEN 'SAI' WHEN 'REVISAO' THEN 'REV' ELSE NULL END;
        IF prefix IS NOT NULL THEN
          number_value := nextval(('seq_movimentacao_' || lower(prefix))::regclass);
          NEW.codigo_movimentacao := prefix || '-' || lpad(number_value::text, greatest(6, length(number_value::text)), '0');
        END IF;
        RETURN NEW;
      END $$;
      CREATE TRIGGER movement_public_code BEFORE INSERT OR UPDATE ON movements FOR EACH ROW EXECUTE FUNCTION assign_movement_public_code();
    `);
  }
}
